name: forward-event-action
description: Forwards events to a webbook with sha1 signature
runs:
  using: node12
  main: index.js
branding:
  icon: activity
  color: red
inputs:
  secret:
    description: The key for hashing as sha1
  webhook:
    description: The webhook URL i.e http://localhost:6500/webhook/github
outputs:
  url:
    description: The full URL that this action is sending payloads to.
